run-name: Check if ${{ inputs.package }} has changed since last successful run of ${{ inputs.workflow-id }}

on:
  # Allows this workflow to be triggered from another workflow
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      workflow-id:
        required: true
        type: string
    outputs:
      changed:
        description: "If package was changed then 1, otherwise an empty string."
        value: ${{ jobs.check-if-package-changed.outputs.changed }}


jobs:
  check-if-package-changed:
    outputs:
      changed: ${{ steps.check-for-changes.outputs.changed }}

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
        with:
          workflow-id: ${{ inputs.workflow-id }}

      - name: Install local version of nx
        run: npm ci --ignore-scripts

      - name: Check for changes
        id: check-for-changes
        run: 'echo "changed=$(
          npx nx print-affected --select=projects
            | sed ''s/, /\n/g''
            | grep -q ''^${{ inputs.package }}$''
          && echo 1
        )" >> $GITHUB_OUTPUT'
