name: 🌎 Deploy Web

on:
  # Allows this workflow to be triggered from another workflow
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    environment: github-pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Typecheck TypeScript
        run: lerna run --scope=*/web typecheck

      - name: Create .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_API_URL: ${{ secrets.API_URL }}
          envkey_GMAPS_KEY: ${{ secrets.GMAPS_KEY }}
          envkey_GTAG_ID: ${{ secrets.GTAG_ID }}
          envkey_LINK_AT_API: ${{ secrets.LINK_AT_API }}
          envkey_LINK_GITHUB: ${{ secrets.LINK_GITHUB }}
          envkey_LINK_GITHUB_CLIENT: ${{ secrets.LINK_GITHUB_CLIENT }}
          envkey_LINK_GITHUB_SERVER: ${{ secrets.LINK_GITHUB_SERVER }}
          envkey_PWA_BASE_URL: ${{ secrets.PWA_BASE_URL }}
          envkey_WS_URL: ${{ secrets.WS_URL }}

      - name: 🛠️ Build
        run: lerna run --scope=*/web build

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/web/dist
